export const ORDER_STATUS_PENDING = "PENDING";
export const ORDER_STATUS_CONFIRMED = "CONFIRMED";
export const ORDER_STATUS_CANCELLED = "CANCELLED";
export const ORDER_STATUS_DISPATCHED = "DISPATCHED";
export const ORDER_STATUS_DELIVERED = "DELIVERED";
